Controllers/AccionesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using TiendaBDWeb.data;
using TiendaBDWeb.Models;


namespace TiendaBDWeb.Controllers
{
    public class AccionesController : Controller
    {
        ProductosDatos proDat = new ProductosDatos();
        public IActionResult ListarProd()
        {
            var ListaPro = proDat.Listar(1, 1);
            return View(ListaPro);
        }


        public IActionResult GuardarProd()
        {
            return View();
        }


        [HttpPost]
        public IActionResult GuardarProd(modeloProductos recProductos)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Error: Datos del producto no válidos.";
                return View();
            }
            var (Exito, MensajeError) = proDat.GuardaModificaProducto(recProductos, 1);

            if (Exito)
            {
                return RedirectToAction("ListarProd");
            }
            else
            {
                TempData["ErrorMessage"] = $"Error: {MensajeError}";
                return View();
            }
        }

        public IActionResult EditarProd(Int32 IdProd)
        {
            var Producto = proDat.RegresaProducto(IdProd, 2);
            return View(Producto);
        }
        [HttpPost]

        public IActionResult EditarProd(modeloProductos numProd)
        {
            if (!ModelState.IsValid) return View();
            var (Exito, MensajeError) = proDat.GuardaModificaProducto(numProd, 2);

            if (Exito) return RedirectToAction("ListarProd");

            else
            {
                TempData["ErrorMessage"] = $"Error: {MensajeError}";
                return View();
            }
        }

        [HttpGet]
        public IActionResult EliminarProd(Int32 datProd)
        {
            var Producto = proDat.RegresaProducto(datProd, 2);
            return View(Producto);
        }
        [HttpPost]
        public IActionResult EliminarProd(modeloProductos datProd)
        {
            var Respuesta = proDat.EliminaProducto(datProd.id_prod_mod);
            if (Respuesta)
                return RedirectToAction("ListarProd");
            else
                return View();
        }

    }
}

Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using TiendaBDWeb.data;
using TiendaBDWeb.Models;

namespace TiendaBDWeb.Controllers
{
    public class ClientesController : Controller
    {
        ClientesDatos clientesDatos = new ClientesDatos();
        public IActionResult listarClientes()
        {
            try
            {
                var clientes = clientesDatos.Listar();
                return View(clientes);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult RegistrarCliente()
        {
            return View();
        }


        [HttpPost]
        public IActionResult RegistrarCliente(modeloClientes dataClientes)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Error: Datos del cliente no válidos.";
                return View();
            }
            var (Exito, MensajeError) = clientesDatos.RegistrarCiente(dataClientes);

            if (Exito)
            {
                return RedirectToAction("ListarClientes");
            }
            else
            {
                TempData["ErrorMessage"] = $"Error: {MensajeError}";
                return View();
            }
        }

        public IActionResult EditarCliente(Int32 idCliente) { 
            var cliente = clientesDatos.RegresaCliente(idCliente);
            return View(cliente);
        }

        [HttpPost]
        public IActionResult EditarCliente(modeloClientes cliente)
        {
            if (!ModelState.IsValid) return View();
            var (Exito, Error) = clientesDatos.EditarCliente(cliente);

            if (Exito) return RedirectToAction("ListarClientes");
            else
            {
                TempData["ErrorMessage"] = $"Error: {Error} cliente: {cliente.id_cli}";
                return View();
            }
        }

        [HttpGet]
        public IActionResult EliminarCliente(Int32 idCliente)
        {
            var cliente = clientesDatos.RegresaCliente(idCliente);
            return View(cliente);
        }
        [HttpPost]
        public IActionResult EliminarCliente(modeloClientes cliente)
        {
            var (Exito, Error) = clientesDatos.EliminarCliente(cliente.id_cli);

            if (Exito) return RedirectToAction("ListarClientes");
            else
            {
                TempData["ErrorMessage"] = $"Error: {Error} No se pudo eliminar el cliente: {cliente.id_cli}";
                return View();
            }
        }



    }
}

Controllers/VentasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using TiendaBDWeb.data;
using TiendaBDWeb.Models;

namespace TiendaBDWeb.Controllers
{
    public class VentasController : Controller
    {
        VentasDato ventasData = new VentasDato();
        ProductosDatos productosData = new ProductosDatos();
        public IActionResult ListarVentas()
        {
            try
            {
                var ListaVentas = ventasData.Listar();
                return View(ListaVentas);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [HttpGet]
        public IActionResult RealizarVenta()
        {
            var productos = productosData.Listar(1, 1);
            var viewModel = new modeloVentaDetalles
            {
                Productos = productos,
                Venta = new modeloVentas {
                    FecVta = DateTime.Now.Date,
                    HorVta = DateTime.Now.ToString("HH:mm")
                }
            };
            return View(viewModel);

        }
        [HttpPost]
        public IActionResult RealizarVenta([FromBody] modeloVentaDetalles jsonData)
        {
            var venta = jsonData.Venta;
            var productosId = jsonData.ProductosId;

            var (exito, error) = ventasData.RegistrarVenta(venta, productosId);
            return Json(jsonData);
            if (exito)
            {
                return Json("Venta realizada con éxito");
            }
            return Json(error);
        }

        [HttpGet]
        public IActionResult EliminarVenta(Int32 idVenta, Int32 idProd)
        {
            var venta = ventasData.RegresaDetalleVenta(idVenta, idProd);
            TempData["ErrorMessage"] = $"{idVenta}   ° {idProd}";
            return View(venta);
        }
        [HttpPost]
        public IActionResult EliminarVenta(modeloVentas venta)
        {
            var (exito, error) = ventasData.EliminarVenta(venta.IdVta, venta.NumProDet);
            if (exito)
            {
                return RedirectToAction("ListarVentas");
            }
            TempData["ErrorMessage"] = $"Error: {error}";
            return View();
        }


        public IActionResult EditarVenta(Int32 idVenta, Int32 idProd) { 
            var venta = ventasData.RegresaDetalleVenta(idVenta, idProd);
            return View(venta.Venta);
        }

        [HttpPost]
        public IActionResult EditarVenta(modeloVentas venta) { 
            var (exito, error)= ventasData.EditarVenta(venta);
            if(exito){
                return RedirectToAction("ListarVentas");
            }
            TempData["ErrorMessage"] = $"Error: {error}";
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TiendaBDWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TiendaBDWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TiendaBDWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acciones" asp-action="ListarProd">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="ListarVentas">Catalogo de ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="ListarClientes">Catalogo de clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TiendaBDWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>